[Application Options]
debuglevel=info
maxpendingchannels=10
alias=policypulse-lnd

[Bitcoin]
bitcoin.active=1
bitcoin.regtest=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=bitcoind
bitcoind.rpcuser=bitcoin
bitcoind.rpcpass=bitcoin
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333

[RPC]
rpclisten=0.0.0.0:10009

[REST]
restlisten=0.0.0.0:8080

[tor]
tor.active=false
